import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { FileText, Download, ShieldCheck } from 'lucide-react';
import { apiClient } from '@lib/axios';

export const ReportingPage: React.FC = () => {
  const { data: reports, isLoading } = useQuery({
    queryKey: ['audit', 'reports'],
    queryFn: async () => {
      try {
        const response = await apiClient.get('/audit/list-reports');
        return response.data.reports || [];
      } catch (e) {
        console.error(e);
        return [];
      }
    }
  });

  const handleDownload = (filename: string) => {
    const baseUrl = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';
    window.open(`${baseUrl}/audit/nrb-report?filename=${encodeURIComponent(filename)}`, '_blank');
  };

  const formatSize = (bytes: number) => {
    if (!bytes) return 'Unknown';
    if (bytes < 1024) return `${bytes} B`;
    return `${(bytes / 1024).toFixed(1)} KB`;
  };

  return (
    <div className="flex flex-col h-full bg-bg-primary text-text-primary p-4 lg:p-6 space-y-6 animate-fade-up">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-bg-panel border border-bg-border flex items-center justify-center shadow-sm">
              <FileText size={20} className="text-accent-teal" />
            </div>
            Reporting &amp; Compliance
          </h1>
          <p className="text-sm text-text-secondary mt-1 ml-13">
            NRB compliance and incident response PDFs generated by the Response Agent.
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 bg-bg-panel border border-bg-border rounded-xl shadow-sm p-6 overflow-hidden flex flex-col">
        <h2 className="text-lg font-semibold mb-4 border-b border-bg-border pb-2">Available Reports</h2>
        
        {isLoading ? (
          <div className="text-text-muted">Loading reports...</div>
        ) : (
          <div className="flex-1 overflow-auto">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {reports?.map((report: any, idx: number) => (
                <div key={idx} className="border border-bg-border rounded-lg p-4 flex flex-col gap-3 hover:border-accent-teal hover:shadow-md transition-all group">
                  <div className="flex items-start justify-between">
                    <div className="p-2 bg-bg-elevated rounded-md text-text-primary">
                      <ShieldCheck size={20} />
                    </div>
                    <span className="text-[10px] font-semibold tracking-wider text-text-muted uppercase px-2 py-1 bg-bg-elevated rounded-full">
                      NRB Compliance
                    </span>
                  </div>
                  
                  <div>
                    <h3 className="font-semibold text-text-primary text-sm truncate" title={report.filename}>
                      {report.filename}
                    </h3>
                    <p className="text-xs text-text-secondary mt-1">
                      {new Date(report.created).toLocaleString()}
                    </p>
                  </div>

                  <div className="mt-auto pt-4 flex items-center justify-between border-t border-bg-border/50">
                    <span className="text-xs font-mono text-text-muted">{formatSize(report.size_bytes)}</span>
                    <button 
                      onClick={() => handleDownload(report.filename)}
                      className="flex items-center gap-1.5 text-xs font-semibold text-accent-teal hover:text-text-primary transition-colors bg-accent-teal/10 hover:bg-bg-elevated px-3 py-1.5 rounded-md"
                    >
                      <Download size={14} />
                      Download
                    </button>
                  </div>
                </div>
              ))}
              {(!reports || reports.length === 0) && (
                <div className="col-span-full text-center py-8 text-text-muted">
                  No reports generated yet. Reports are created automatically when a CRITICAL threat is detected.
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ReportingPage;
