#!/usr/bin/env python3
"""
evaluate_test_csv.py

Loads the combined testing dataset (e.g. cleaned_dataset_test.csv) generated by 
Cleaned_behaviour.py, extracts the 14-dimensional sequences using train_behavior's 
logic, and evaluates the trained BehaviorAgent against it.

Usage:
    python evaluate_test_csv.py <path_to_cleaned_dataset_test.csv>
"""

import sys
import logging
from pathlib import Path
import pandas as pd
import numpy as np

import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from agents.behaviour_agent import BehaviorAgent
from training.train_behavior import prepare_sequences
from config import MODELS_DIR

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

def main():
    if len(sys.argv) < 2:
        print("Usage: python evaluate_test_csv.py <cleaned_dataset_test.csv>")
        sys.exit(1)
        
    test_csv_path = Path(sys.argv[1])
    if not test_csv_path.exists():
        logger.error(f"Test dataset not found: {test_csv_path}")
        sys.exit(1)
        
    logger.info("Loading test dataset...")
    df = pd.read_csv(test_csv_path)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    logger.info("Extracting sequences using unified logic...")
    # prepare_sequences returns (normal_seqs, anomaly_seqs)
    normal_seqs, anomaly_seqs = prepare_sequences(df)
    
    total_seqs = len(normal_seqs) + len(anomaly_seqs)
    logger.info(f"Extracted {total_seqs} total sequences (seq_len=20).")
    logger.info(f"  - Normal sequences:  {len(normal_seqs)}")
    logger.info(f"  - Anomaly sequences: {len(anomaly_seqs)}")
    
    if total_seqs == 0:
        logger.warning("No complete sequences of length 20 found in the test dataset.")
        sys.exit(0)
        
    try:
        logger.info("Loading Behavior Agent...")
        agent = BehaviorAgent.load(models_dir=MODELS_DIR, device="cpu")
    except FileNotFoundError as e:
        logger.error(f"Could not load agent: {e}")
        logger.error("Make sure you have trained the model with 'python train_behavior.py' first.")
        sys.exit(1)
        
    logger.info(f"Agent loaded. Threshold: {agent.threshold:.6f}")
    
    # Evaluate Normal Sequences (Expected: is_anomaly = False)
    false_positives = 0
    if len(normal_seqs) > 0:
        for seq in normal_seqs:
            alert = agent.score_sequence(seq)
            if alert.is_anomaly:
                false_positives += 1
                
    # Evaluate Anomaly Sequences (Expected: is_anomaly = True)
    true_positives = 0
    if len(anomaly_seqs) > 0:
        for seq in anomaly_seqs:
            alert = agent.score_sequence(seq)
            if alert.is_anomaly:
                true_positives += 1
                
    # Print Report
    print("\n" + "="*50)
    print("EVALUATION RESULTS ON TEST DATASET")
    print("="*50)
    
    if len(normal_seqs) > 0:
        tn = len(normal_seqs) - false_positives
        fpr = (false_positives / len(normal_seqs)) * 100
        print(f"Normal Sequences Scored : {len(normal_seqs)}")
        print(f"Correctly identified    : {tn}")
        print(f"False Positives         : {false_positives}")
        print(f"False Positive Rate     : {fpr:.2f}%\n")
    else:
        print("No normal sequences available for False Positive Rate calculation.\n")
        
    if len(anomaly_seqs) > 0:
        fn = len(anomaly_seqs) - true_positives
        dr = (true_positives / len(anomaly_seqs)) * 100
        print(f"Anomaly Sequences Scored: {len(anomaly_seqs)}")
        print(f"Correctly identified    : {true_positives}")
        print(f"False Negatives         : {fn}")
        print(f"Detection Rate (Recall) : {dr:.2f}%\n")
    else:
        print("No anomaly sequences available for Detection Rate calculation.\n")
        
    print("="*50)

if __name__ == "__main__":
    main()
